feat: raw realization registration
deremenko/hospital-project-frontend--redux-react-styled-component- pull request #3
Opened 2024-02-13 06:14 UTC by deremenko

registration-page realization

2024-02-14 08:50 UTC, baklanovairina requested changes

2024-02-14 08:50 UTC, baklanovairina commented on src/App.jsx
> +    <RegistrationPage>
подключи пожалуйста роуты

2024-02-14 08:50 UTC, baklanovairina commented on src/App.jsx
> +function App() {
стрелочная

2024-02-14 08:50 UTC, baklanovairina commented on src/components/Button/index.jsx
> +const Button = ({ textButton, icon, nameIcon, actionButton }) => {
перенеси UI элементы в папку UI

2024-02-14 08:50 UTC, baklanovairina commented on src/components/Form/index.jsx
> +      <StyledP>{title}</StyledP>
ну это не StyledP - а хотя бы StyledHeader

2024-02-14 08:50 UTC, baklanovairina commented on src/components/Form/index.jsx
> +      {children}
сюда также можно вынести кнопку и ссылку

2024-02-14 08:50 UTC, baklanovairina commented on src/components/Header/index.jsx
> +import { StyledHeader, StyledImg, StyledText } from "./styles";
стили импортятся в конце

2024-02-14 08:50 UTC, baklanovairina commented on src/components/Header/index.jsx
> +  const { data } = useContext(Context);
ну не data и по идеи ты должен через деструктуризацию сразу заголовок достать, а не целый объект, который не нужен

2024-02-14 08:50 UTC, baklanovairina commented on src/components/Header/index.jsx
> +      <StyledText>{data.title}</StyledText>
StyledHeader или StyledTitle

2024-02-14 08:50 UTC, baklanovairina commented on src/components/Header/styles.js
> +  width :45px;
пробел не там

2024-02-14 08:50 UTC, baklanovairina commented on src/components/InputLine/index.jsx
> +const InputLine = ({
CustomInput

2024-02-14 08:50 UTC, baklanovairina commented on src/components/InputLine/index.jsx
> +      <label>{ label }</label>
пробелы лишние

2024-02-14 08:50 UTC, baklanovairina commented on src/components/InputLine/index.jsx
> +      <label>{ label }</label>
добавь htmlFor

2024-02-14 08:50 UTC, baklanovairina commented on src/components/InputLine/index.jsx
> +        onChange={(event) => handleInputChange(event)}
а прям весь объект event нужен?

2024-02-14 08:50 UTC, baklanovairina commented on src/components/InputLine/index.jsx
> +        name={nameFieldObject}
а value где?

2024-02-14 08:50 UTC, baklanovairina commented on src/components/RegistrationPage/InteractionZone/index.jsx
> +import { StyledInteractionZone, StyledImg, StyledContentContainer, StyledLink } from "./styles";
порядок импортов

2024-02-14 08:50 UTC, baklanovairina commented on src/components/RegistrationPage/InteractionZone/index.jsx
> +const InteractionZone = ({ handleInputChange, sendRegistrationForm }) => {
почему у тебя страница регистрации делится на еще что-то? 
что такое вообще InteractionZone? 
Если это компонент страницы, то здесь уже должна полностью собираться страница
Где сам компонент RegistrationPage?

и RegistrationPage перенеси в папку pages

2024-02-14 08:50 UTC, baklanovairina commented on src/components/RegistrationPage/InteractionZone/index.jsx
> +const InteractionZone = ({ handleInputChange, sendRegistrationForm }) => {
и где логика?

2024-02-14 08:50 UTC, baklanovairina commented on src/components/RegistrationPage/InteractionZone/index.jsx
> +            typeInput="text"
value?

2024-02-14 08:50 UTC, baklanovairina commented on src/components/RegistrationPage/InteractionZone/index.jsx
> +            nameFieldObject="login"
просто name, не усложняй

2024-02-14 08:50 UTC, baklanovairina commented on src/components/RegistrationPage/InteractionZone/index.jsx
> +            typeInput="text"
просто type

2024-02-14 08:50 UTC, baklanovairina commented on src/components/RegistrationPage/MainLaylout/index.jsx
> +const MainLaylout = () => {
это максимально странное деление, бессмысленное, объединяй в один компонент страницы

2024-02-14 08:50 UTC, baklanovairina commented on src/components/RegistrationPage/MainLaylout/index.jsx
> +import StyledMainLaylout from "./styles";
порядок

2024-02-14 08:50 UTC, baklanovairina commented on src/components/RegistrationPage/MainLaylout/index.jsx
> +  const [inputValues, setInputValues] = useState({
это не inputValues
грамотно называй объект

2024-02-14 08:50 UTC, baklanovairina commented on src/components/RegistrationPage/MainLaylout/index.jsx
> +  const { login, password, repeatPassword } = inputValues;
нельзя делать деструктуризацию здесь

2024-02-14 08:50 UTC, baklanovairina commented on src/components/RegistrationPage/MainLaylout/index.jsx
> +  const dispatch = useDispatch();
создай хук useActions на базе useDispatch

2024-02-14 08:50 UTC, baklanovairina commented on src/components/RegistrationPage/MainLaylout/index.jsx
> +import { sendObject } from "../../../store/actionCreators/registration"
sendObject? Может все такие регистрация, а не отправить объект

2024-02-14 08:50 UTC, baklanovairina commented on src/components/RegistrationPage/MainLaylout/index.jsx
> +  const sendRegistrationForm = () => {
тоже проблема нейминга здесь

2024-02-14 08:50 UTC, baklanovairina commented on src/components/RegistrationPage/MainLaylout/index.jsx
> +    if (inputValues.password === inputValues.repeatPassword) {
валидацию добавь

2024-02-14 08:50 UTC, baklanovairina commented on src/components/RegistrationPage/MainLaylout/index.jsx
> +    setInputValues((prevState) => ({
не надо через prevState делать
```
setNewUser({
  ...newUser,
  [key]: event.target.value
})
```

2024-02-14 08:50 UTC, baklanovairina commented on src/components/RegistrationPage/MainLaylout/index.jsx
> +      </Header>
зачем нужен закрыващий тег? У тебя нет здесь чилдренов

2024-02-14 08:50 UTC, baklanovairina commented on src/contexts/context.js
> +const ContextProvider = ({ children }) => {
так с
это файл контекст и здесь только контекст создается
а провайдет будет в отдельном файле и папке providers

и где логика определения и выбор нужного заголовка в зависимости от страницы

2024-02-14 08:50 UTC, baklanovairina commented on src/contexts/context.js
> +  const [data, setData] = useState({
нейминг правь

2024-02-14 08:50 UTC, baklanovairina commented on src/helpers/clearObject.js
> +export const clearObject = (Object) => {
что-то явно лишнее и ненужное, нигде не используется

2024-02-14 08:50 UTC, baklanovairina commented on src/index.js
>      <Provider store={store}>
оберни все в роуты

2024-02-14 08:50 UTC, baklanovairina commented on src/services/registaration.js
> +const API_URL = 'http://localhost:8000';
это константы

2024-02-14 08:50 UTC, baklanovairina commented on src/services/registaration.js
> +    const response = await axios.post(`${API_URL}/user/registration`, objectData);
здесь будет только сам запрос try/catch вообще у тебя в action-creators и там же обработка ошибок

2024-02-14 08:50 UTC, baklanovairina commented on src/store/actionCreators/registration.js
> +import { sendRegistrationForm } from '../../services/registaration.js';
action-creators - нейминг файлов в сторе по кебаб кейс

2024-02-14 08:50 UTC, baklanovairina commented on src/services/registaration.js
> +import axios from 'axios';
src/services/registaration.js - не registaration, а user, так как здесь будут хранится все сервисы для юзера

2024-02-14 08:50 UTC, baklanovairina commented on src/store/actionCreators/registration.js
> +  sendObjectError,
ну очень некорректный нейминг, там можно прям все назвать и потом 100 лет разбираться

2024-02-14 08:50 UTC, baklanovairina commented on src/store/actionCreators/registration.js
> +} from '../actions/registration.js';
тоже путь поправь на user.js

2024-02-14 08:50 UTC, baklanovairina commented on src/store/actionCreators/registration.js
> +export const sendObject = (objectData) => async (dispatch) => {
нейминг везде исправь, никто иначе никогда не поймет, что это связано с регистрацией

2024-02-14 08:50 UTC, baklanovairina commented on src/store/actions/registration.js
> +  SEND_REGISTRATION_FORM_ERROR
пожалуйста еще раз посмотри пример нейминга в файле прилагаемом в материалах

2024-02-14 08:50 UTC, baklanovairina commented on src/store/enums/registration.js
> +export { SEND_REGISTRATION_FORM, SEND_REGISTRATION_FORM_SUCCESS, SEND_REGISTRATION_FORM_ERROR };
перенос строк

2024-02-14 08:50 UTC, baklanovairina commented on src/store/index.js
> +import reducerRegistration from "./reducers/reducerRegistration.js";
userReducer так там будут хранится все что связано с юзерами

2024-02-14 08:50 UTC, baklanovairina commented on src/store/reducers/reducerRegistration.js
> +  registrationForm: [],
ну вообще не форм
и причем тут массив
тебе с бэка возвращается токен, поэтому будет 
isAuth
userData

ну и error

2024-02-14 08:50 UTC, baklanovairina commented on src/store/reducers/reducerRegistration.js
> +        tasks: [...state.tasks, action.payload],
откуда таски?? и снова массив какой то

2024-02-14 10:19 UTC, deremenko commented on src/App.jsx
> +function App() {
corrected

2024-02-14 10:57 UTC, deremenko commented on src/components/Button/index.jsx
> +const Button = ({ textButton, icon, nameIcon, actionButton }) => {
corrected

2024-02-14 11:03 UTC, deremenko commented on src/App.jsx
> +    <RegistrationPage>
corrected

2024-02-14 11:04 UTC, deremenko commented on src/components/Form/index.jsx
> +      <StyledP>{title}</StyledP>
corrected

2024-02-14 11:10 UTC, deremenko commented on src/components/Header/index.jsx
> +import { StyledHeader, StyledImg, StyledText } from "./styles";
corrected

2024-02-14 11:26 UTC, deremenko commented on src/components/Header/index.jsx
> +  const { data } = useContext(Context);
corrected

2024-02-14 11:28 UTC, deremenko commented on src/components/Header/styles.js
> +  width :45px;
corrected

2024-02-14 11:29 UTC, deremenko commented on src/components/Header/index.jsx
> +      <StyledText>{data.title}</StyledText>
corrected

2024-02-14 11:29 UTC, deremenko commented on src/components/InputLine/index.jsx
> +const InputLine = ({
corrected

2024-02-14 11:30 UTC, deremenko commented on src/components/InputLine/index.jsx
> +      <label>{ label }</label>
corrected

2024-02-14 11:42 UTC, deremenko commented on src/components/InputLine/index.jsx
> +      <label>{ label }</label>
corrected

2024-02-14 11:45 UTC, deremenko commented on src/components/InputLine/index.jsx
> +        onChange={(event) => handleInputChange(event)}
corrected

2024-02-14 12:05 UTC, deremenko commented on src/components/RegistrationPage/InteractionZone/index.jsx
> +import { StyledInteractionZone, StyledImg, StyledContentContainer, StyledLink } from "./styles";
corrected

2024-02-14 12:55 UTC, deremenko commented on src/components/RegistrationPage/InteractionZone/index.jsx
> +const InteractionZone = ({ handleInputChange, sendRegistrationForm }) => {
corrected

2024-02-14 12:55 UTC, deremenko commented on src/components/RegistrationPage/InteractionZone/index.jsx
> +            typeInput="text"
corrected

2024-02-14 12:55 UTC, deremenko commented on src/components/RegistrationPage/MainLaylout/index.jsx
> +const MainLaylout = () => {
corrected

2024-02-14 13:04 UTC, deremenko commented on src/components/RegistrationPage/MainLaylout/index.jsx
> +import StyledMainLaylout from "./styles";
corrected

2024-02-14 13:04 UTC, deremenko commented on src/components/RegistrationPage/InteractionZone/index.jsx
> +            typeInput="text"
corrected

2024-02-14 13:05 UTC, deremenko commented on src/components/RegistrationPage/InteractionZone/index.jsx
> +            nameFieldObject="login"
corrected

2024-02-14 13:27 UTC, deremenko commented on src/components/RegistrationPage/MainLaylout/index.jsx
> +  const [inputValues, setInputValues] = useState({
corrected

2024-02-14 13:31 UTC, deremenko commented on src/components/RegistrationPage/MainLaylout/index.jsx
> +  const { login, password, repeatPassword } = inputValues;
corrected

2024-02-14 13:35 UTC, deremenko commented on src/components/RegistrationPage/MainLaylout/index.jsx
> +import { sendObject } from "../../../store/actionCreators/registration"
corrected

2024-02-14 13:37 UTC, deremenko commented on src/components/RegistrationPage/MainLaylout/index.jsx
> +    setInputValues((prevState) => ({
corrected

2024-02-14 13:37 UTC, deremenko commented on src/components/RegistrationPage/MainLaylout/index.jsx
> +      </Header>
corrected

2024-02-14 13:42 UTC, deremenko commented on src/helpers/clearObject.js
> +export const clearObject = (Object) => {
corrected

2024-02-14 13:43 UTC, deremenko commented on src/services/registaration.js
> +    const response = await axios.post(`${API_URL}/user/registration`, objectData);
corrected

2024-02-14 13:45 UTC, deremenko commented on src/store/actionCreators/registration.js
> +import { sendRegistrationForm } from '../../services/registaration.js';
corrected

2024-02-14 13:46 UTC, deremenko commented on src/services/registaration.js
> +import axios from 'axios';
corrected

2024-02-14 13:48 UTC, deremenko commented on src/store/actionCreators/registration.js
> +} from '../actions/registration.js';
corrected

2024-02-14 13:48 UTC, deremenko commented on src/store/actionCreators/registration.js
> +export const sendObject = (objectData) => async (dispatch) => {
corrected

2024-02-14 13:49 UTC, deremenko commented on src/store/enums/registration.js
> +export { SEND_REGISTRATION_FORM, SEND_REGISTRATION_FORM_SUCCESS, SEND_REGISTRATION_FORM_ERROR };
corrected

2024-02-14 13:51 UTC, deremenko commented on src/store/index.js
> +import reducerRegistration from "./reducers/reducerRegistration.js";
corrected

2024-02-15 01:45 UTC, deremenko commented on src/components/InputLine/index.jsx
> +        name={nameFieldObject}
corrected

2024-02-15 01:52 UTC, deremenko commented on src/components/RegistrationPage/MainLaylout/index.jsx
> +  const sendRegistrationForm = () => {
corrected

2024-02-15 07:43 UTC, deremenko commented on src/services/registaration.js
> +const API_URL = 'http://localhost:8000';
maybe corrected

2024-02-15 07:43 UTC, deremenko commented on src/index.js
>      <Provider store={store}>
corrected

2024-02-15 07:53 UTC, deremenko commented on src/store/actionCreators/registration.js
> +  sendObjectError,
corrected

2024-02-15 07:53 UTC, deremenko commented on src/store/actions/registration.js
> +  SEND_REGISTRATION_FORM_ERROR
maybe corrected

2024-02-15 07:54 UTC, deremenko commented on src/store/reducers/reducerRegistration.js
> +  registrationForm: [],
corrected

2024-02-15 07:54 UTC, deremenko commented on src/store/reducers/reducerRegistration.js
> +        tasks: [...state.tasks, action.payload],
corrected

2024-02-15 07:55 UTC, deremenko commented on src/components/RegistrationPage/MainLaylout/index.jsx
> +  const dispatch = useDispatch();
maybe corrected

2024-02-16 08:06 UTC, baklanovairina requested changes

2024-02-16 08:06 UTC, baklanovairina commented on src/App.jsx
> +      <Route path="/registration" element={<RegistrationPage />}/>
перед /> ставь всегда пробел пожалуйста

2024-02-16 08:06 UTC, baklanovairina commented on src/components/Button/index.jsx
> +const Button = ({ textButton, icon, nameIcon, actionButton }) => {
не перенес в UI 
кнопка это тоже UI компонент

2024-02-16 08:06 UTC, baklanovairina commented on src/components/Button/index.jsx
> +      <span>{textButton}</span>
это тег p лучше

2024-02-16 08:06 UTC, baklanovairina commented on src/components/Button/index.jsx
> +    <StyledButton onClick={actionButton}>
type?

2024-02-16 08:06 UTC, baklanovairina commented on src/components/Form/index.jsx
> +      {children}
добавь сюда кнопку и ссылку из формы

2024-02-16 08:06 UTC, baklanovairina commented on src/components/Form/styles.js
> +
2 лишние пустые строки удали

2024-02-16 08:06 UTC, baklanovairina commented on src/components/Header/index.jsx
> +
здесь 1 лишняя пустая строка

2024-02-16 08:06 UTC, baklanovairina commented on src/components/Page/Registration/index.jsx
> +import useActions from "../../../hook/useActions"
хуки идут после компонентов

2024-02-16 08:06 UTC, baklanovairina commented on src/components/Page/Registration/index.jsx
> +import logoIcon from "../../../img/logo.png";
картинки почти последние, до стилей

2024-02-16 08:06 UTC, baklanovairina commented on src/components/Page/Registration/index.jsx
> +          value: newUser.login.value,
не очень понимаю, зачем ты обновляешь value при ошибке? Только error нужно

2024-02-16 08:06 UTC, baklanovairina commented on src/components/Page/Registration/index.jsx
> +          value: newUser.password.value,
здесь аналогично

2024-02-16 08:06 UTC, baklanovairina commented on src/components/Page/Registration/index.jsx
> +          value: newUser.repeatPassword.value,
и здесь

2024-02-16 08:06 UTC, baklanovairina commented on src/components/Page/Registration/index.jsx
> +              idLabel="twoPassword"
repeatPassword

2024-02-16 08:06 UTC, baklanovairina commented on src/components/Page/Registration/index.jsx
> +            <Button textButton="Зарегистрироваться" actionButton={createNewUser} />
type

2024-02-16 08:06 UTC, baklanovairina commented on src/components/Page/Registration/index.jsx
> +            <StyledLink href="">Авторизироваться</StyledLink>
здесь Link используй из router-dom

2024-02-16 08:06 UTC, baklanovairina commented on src/components/UI/CustomInput/index.jsx
> +        {error && <StyledError>{` ${error}`}</StyledError>}
почему ошибки внутри лейбла? 
и для ошибки создай отдельный компонент, давай вообще воспользуемся material ui, возьми оттуда снэкбар, вынеси его в отдельный компонент и переиспользуй везде, где нужен вывод ошибки с бэка

под инпутами ошибку оставь для валидации на фронте, просто из тега label вытащи ее

2024-02-16 08:06 UTC, baklanovairina commented on src/components/UI/CustomInput/styles.js
> +const StyledError = styled.span`
отступы

2024-02-16 08:06 UTC, baklanovairina commented on src/helpers/validatePassword.js
> +const validatePassword = (text) => {
не обязательно пароля, не конкретизируй хэлперс функции

2024-02-16 08:06 UTC, baklanovairina commented on src/helpers/validateTextLength.js
> +  return data.trim().length >= 6;
а если нужно будет 7? 10 символов? Будешь новую функцию писать аналогичную?

2024-02-16 08:06 UTC, baklanovairina commented on src/hook/useActions.js
> +import { registration } from "../store/action-creators/user";
объедени все action-creators в одном файле и импортируй его здесь, чтобы постоянно хук не править

2024-02-16 08:06 UTC, baklanovairina commented on src/services/user.js
> +export const registerUser = async (objectData) => {
objectData - поправь название, например на user или newUser ну на краняк UserData

2024-02-16 08:06 UTC, baklanovairina commented on src/services/user.js
> +  const { login, password } = objectData;
зачем??

2024-02-16 08:06 UTC, baklanovairina commented on src/store/action-creators/user.js
> +export const registration = (objectData) => async (dispatch) => {
тоже не objectData, поправь нейминг

2024-02-16 08:06 UTC, baklanovairina commented on src/store/actions/user.js
> +export const submitRegistrationSuccess = (user) => ({
```
export const submitRegistrationSuccess = (payload) => ({
  type: SUBMIT_REGISTRATION_SUCCESS,
  payload
});
```

2024-02-16 08:06 UTC, baklanovairina commented on src/store/enums/user.js
> +const SUBMIT_REGISTRATION_ERROR  = 'SUBMIT_REGISTRATION_ERROR '
пробел есть лишний в конце

2024-02-16 09:16 UTC, deremenko commented on src/store/enums/user.js
> +const SUBMIT_REGISTRATION_ERROR  = 'SUBMIT_REGISTRATION_ERROR '
corrected

2024-02-16 09:16 UTC, deremenko commented on src/App.jsx
> +      <Route path="/registration" element={<RegistrationPage />}/>
corrected

2024-02-16 09:28 UTC, deremenko commented on src/components/Button/index.jsx
> +      <span>{textButton}</span>
corrected

2024-02-16 09:31 UTC, deremenko commented on src/components/Button/index.jsx
> +    <StyledButton onClick={actionButton}>
corrected

2024-02-16 09:47 UTC, deremenko commented on src/components/Form/styles.js
> +
corrected

2024-02-16 09:47 UTC, deremenko commented on src/components/Header/index.jsx
> +
corrected

2024-02-16 09:48 UTC, deremenko commented on src/components/Page/Registration/index.jsx
> +import useActions from "../../../hook/useActions"
corrected

2024-02-16 10:05 UTC, deremenko commented on src/components/Page/Registration/index.jsx
> +import logoIcon from "../../../img/logo.png";
corrected

2024-02-16 10:05 UTC, deremenko commented on src/components/Page/Registration/index.jsx
> +          value: newUser.login.value,
corrected

2024-02-16 10:05 UTC, deremenko commented on src/components/Page/Registration/index.jsx
> +          value: newUser.password.value,
corrected

2024-02-16 10:05 UTC, deremenko commented on src/components/Page/Registration/index.jsx
> +          value: newUser.repeatPassword.value,
corrected

2024-02-16 10:06 UTC, deremenko commented on src/components/Page/Registration/index.jsx
> +              idLabel="twoPassword"
corrected

2024-02-16 10:06 UTC, deremenko commented on src/components/Page/Registration/index.jsx
> +            <Button textButton="Зарегистрироваться" actionButton={createNewUser} />
corrected

2024-02-16 10:08 UTC, deremenko commented on src/components/UI/CustomInput/styles.js
> +const StyledError = styled.span`
corrected

2024-02-16 10:21 UTC, deremenko commented on src/helpers/validateTextLength.js
> +  return data.trim().length >= 6;
corrected

2024-02-16 10:21 UTC, deremenko commented on src/services/user.js
> +export const registerUser = async (objectData) => {
corrected

2024-02-16 10:21 UTC, deremenko commented on src/services/user.js
> +  const { login, password } = objectData;
corrected

2024-02-16 10:22 UTC, deremenko commented on src/store/action-creators/user.js
> +export const registration = (objectData) => async (dispatch) => {
corrected

2024-02-16 10:34 UTC, deremenko commented on src/store/actions/user.js
> +export const submitRegistrationSuccess = (user) => ({
corrected

2024-02-16 10:40 UTC, deremenko commented on src/components/Page/Registration/index.jsx
> +            <StyledLink href="">Авторизироваться</StyledLink>
corrected

2024-02-16 11:02 UTC, deremenko commented on src/hook/useActions.js
> +import { registration } from "../store/action-creators/user";
corrected

2024-02-16 11:04 UTC, deremenko commented on src/helpers/validatePassword.js
> +const validatePassword = (text) => {
corrected

2024-02-19 07:23 UTC, baklanovairina requested changes

2024-02-19 07:23 UTC, baklanovairina commented on src/components/Page/Registration/index.jsx
> +import { useSelector } from 'react-redux';
порядок импортов

2024-02-19 07:23 UTC, baklanovairina commented on src/components/Page/Registration/index.jsx
> +  console.log(errorFromBackend)
консоль удали

2024-02-19 07:23 UTC, baklanovairina commented on src/components/Page/Registration/index.jsx
> +      setErrorOpen(false);
не очень понятно почему ты при наличии ошибки закрываешь окно с ошибкой?

2024-02-19 07:23 UTC, baklanovairina commented on src/components/Page/Registration/index.jsx
> +  const { registration }  = useActions();
подними до useEffect

2024-02-19 07:23 UTC, baklanovairina commented on src/components/Page/Registration/index.jsx
> +    <ErrorSnackbar open={errorOpen} handleClose={handleSnackbarClose} errorMessage={errorMessage} />
перенос строк

2024-02-19 07:45 UTC, merged