feat: add basic authorization functionality
deremenko/hospital-project-frontend--redux-react-styled-component- pull request #4
Opened 2024-02-19 08:14 UTC by deremenko

add basic authorization functionality

2024-02-20 07:19 UTC, baklanovairina requested changes

2024-02-20 07:19 UTC, baklanovairina commented on src/components/Page/Authorization/index.jsx
> +import { useSelector } from 'react-redux';
порядок!

2024-02-20 07:19 UTC, baklanovairina commented on src/components/Page/Authorization/index.jsx
> +  const [errorMessage, setErrorMessage] = useState('');
я вот думаю, что наверно эти 2 стейта тоже можно объединить в 1, в виде объекта

2024-02-20 07:19 UTC, baklanovairina commented on src/components/Page/Authorization/index.jsx
> +  const navigate = useNavigate();
и зачем? У тебя за перенаправление будет отвечать хок (смотри ТЗ)

2024-02-20 07:19 UTC, baklanovairina commented on src/components/Page/Authorization/index.jsx
> +    if (newUser.login.value.trim() === "") {
это newUser.login.value.trim() === ""
замени на !newUser.login.value.trim()

2024-02-20 07:19 UTC, baklanovairina commented on src/components/Page/Authorization/index.jsx
> +    if (newUser.password.value.trim() === "") {
тоже самое

2024-02-20 07:19 UTC, baklanovairina commented on src/services/user.js
> +  return response.cookie;
response.cookie?? с чего бы вдруг мы специально возвращаем куки в компонент?
там также response.data

2024-02-20 08:32 UTC, deremenko commented on src/components/Page/Authorization/index.jsx
> +import { useSelector } from 'react-redux';
corrected

2024-02-20 08:32 UTC, deremenko commented on src/services/user.js
> +  return response.cookie;
corrected

2024-02-20 08:33 UTC, deremenko commented on src/components/Page/Authorization/index.jsx
> +    if (newUser.password.value.trim() === "") {
corrected

2024-02-20 08:33 UTC, deremenko commented on src/components/Page/Authorization/index.jsx
> +    if (newUser.login.value.trim() === "") {
corrected

2024-02-20 08:41 UTC, deremenko commented on src/components/Page/Authorization/index.jsx
> +  const [errorMessage, setErrorMessage] = useState('');
corrected

2024-02-20 08:58 UTC, deremenko commented on src/components/Page/Authorization/index.jsx
> +  const navigate = useNavigate();
Maybe corrected

2024-02-21 06:56 UTC, baklanovairina requested changes

2024-02-21 06:56 UTC, baklanovairina commented on src/components/privateHOC/index.jsx
> +const withAuthRedirect = (WrappedComponent, authenticated) => {
во-первых, название
назови, пожалуйста корректнее, например PrivateRoute или ProtectedRoute и папку и компонент (они всегда должны иметь одинаковое название, почему то ты это забыл)

второе - передаем только компонент в пропсах
isAuth ты получаешь из редакс 
поэтому из этого третье - что это такое authenticated???

2024-02-21 06:56 UTC, baklanovairina commented on src/components/privateHOC/index.jsx
> +    } else {
зачем тут else, если есть return??

2024-02-21 07:46 UTC, merged