feat: main-page and addReception logic
deremenko/hospital-project-frontend--redux-react-styled-component- pull request #5
Opened 2024-02-22 07:42 UTC by deremenko

Main part of the main page

2024-02-22 08:30 UTC, baklanovairina requested changes

2024-02-22 08:30 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +  const [selectedOption, setSelectedOption] = useState('');
нейминг некорректный, представь, что у тебя на странице 3 селектора, как понять че это состояние??

2024-02-22 08:30 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +  const [errorMessage, setErrorMessage] = useState('');
объединяй в 1 стейт эти 2

2024-02-22 08:30 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +  const receptions = useSelector((state) => state.user.receptions);
а здесь ошибка не нужна?? 
и почему user???
должно быть вроде state.receptions
где то напортачил в редаксе

2024-02-22 08:30 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +  const { loadReceptions, createReception }  = useActions();
loadReceptions - лучше getReceptions назови функцию

2024-02-22 08:30 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +  const [selectedOption, setSelectedOption] = useState('');
стоп, это селектор доктора?? А зачем тебе второй стейт для определения доктора? У тебя уже есть newReception и поле doctor в нем.
Незачем его дважды отслеживать

2024-02-22 08:30 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +    setNewReception((prevReception) => ({
дублирование, ты это уже в handleInputChange делаешь

2024-02-22 08:30 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +    setErrorOpen(false);
функция ради функции

2024-02-22 08:30 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +    setNewReception({
зачем для этого отдельную функцию создавать?? 
это всего раз используется

2024-02-22 08:30 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +  const setReception = () => {
не называй функции через set 
это вносит путаницу со стейтами

2024-02-22 08:30 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +      patient: newReception.name.value.trim(),
перед этим добавь валидацию - проверку на пустые поля
и проверку даты - что нельзя задать ее прошедшим числом

2024-02-22 08:30 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +      <CustomButton
табы

2024-02-22 08:30 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +        className="big-size-button "
классы по БЭМ и согласно неймингу компонента должны быть

2024-02-22 08:30 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +          className="resectionInput"
тоже нейминг хромает не по БЭМ и не по неймингу компонента

2024-02-22 08:30 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +        <Reception
может тогда ReceptionS
это же не один прием

2024-02-22 08:30 UTC, baklanovairina commented on src/components/Reception/index.jsx
> +          <StyledTitleText className="name-field">Имя</StyledTitleText>
через map делай

2024-02-22 08:30 UTC, baklanovairina commented on src/components/Reception/index.jsx
> +            <StyledContent>{reception.patient}</StyledContent>
каждая строка это отдельный компонент тоже
а здесь просто мапь эти строки

2024-02-22 08:30 UTC, baklanovairina commented on src/components/Reception/styles.js
> +  }
скобка?

2024-02-22 08:30 UTC, baklanovairina commented on src/components/ReceptionForm/index.jsx
> +      {children}
да пиши здесь уже всю форму, ты ее в данном приложении все равно нигде не переиспользуешь, нет смысл передавать чилдренами поля

2024-02-22 08:30 UTC, baklanovairina commented on src/components/UI/CustomButton/index.jsx
> +    <StyledButton type={type} onClick={actionButton} className={className}>
делай перенос, когда больше 2х атрибутов или пропсов

2024-02-22 08:30 UTC, baklanovairina commented on src/components/UI/CustomButton/index.jsx
> +  className }) => {
```
  className 
}) => {
```

2024-02-22 08:30 UTC, baklanovairina commented on src/http/index.js
> +  return config;
какой то не дописанный у тебя interceptors
без рефреша

2024-02-22 08:30 UTC, baklanovairina commented on src/http/index.js
> +import { API_URL } from "../constants"
;

2024-02-22 08:30 UTC, baklanovairina commented on src/services/user.js
> +export const requestReceptions = async () => {
что в сервисах юзеров забыли приемы??
и нейминг ужасный, никто не называем сервисы через request
а то прям непонятно, как будто что это запрос
это будет getReceptions

2024-02-22 08:30 UTC, baklanovairina commented on src/services/user.js
> +  const response = await httpClient.get(`${API_URL}/reception/`);
httpClient- api назови это api
это уже привычное название для всех

2024-02-22 08:30 UTC, baklanovairina commented on src/services/user.js
> +export const sendReception = async (reception) => {
не отправить прием, а создать прием: createReception

2024-02-22 08:30 UTC, baklanovairina commented on src/services/user.js
> +  const response = await httpClient.post(`${API_URL}/reception/`, reception);
почему везде слэш лишний в конце?

2024-02-22 08:30 UTC, baklanovairina commented on src/store/action-creators/user.js
> +const createReception = (reception) => async (dispatch) => {
опять что забыли приемы в юзерах??

2024-02-22 08:30 UTC, baklanovairina commented on src/store/action-creators/user.js
> +    console.log(reception);
консоль!

2024-02-22 08:30 UTC, baklanovairina commented on src/store/actions/user.js
> +export const getReceptionsError = (error) => ({
ну ты понял, делай рефакторинг

2024-02-22 08:30 UTC, baklanovairina commented on src/store/reducers/user-reducer.js
> +    case GET_RECEPTIONS_SUCCESS:
везде сделай рефакторинг

2024-02-22 08:47 UTC, deremenko commented on src/components/Page/Main/index.jsx
> +  const [selectedOption, setSelectedOption] = useState('');
maybe fix

2024-02-22 08:59 UTC, deremenko commented on src/components/Page/Main/index.jsx
> +  const [errorMessage, setErrorMessage] = useState('');
corrected

2024-02-22 09:04 UTC, deremenko commented on src/components/Page/Main/index.jsx
> +  const { loadReceptions, createReception }  = useActions();
corrected

2024-02-22 09:10 UTC, deremenko commented on src/components/Page/Main/index.jsx
> +  const { loadReceptions, createReception }  = useActions();
Взял слово fetch, так как get уже используется в action

2024-02-22 09:13 UTC, deremenko commented on src/components/Page/Main/index.jsx
> +  const [selectedOption, setSelectedOption] = useState('');
corrected. Тут прям совсем глупо получилось, да...

2024-02-22 09:14 UTC, deremenko commented on src/components/Page/Main/index.jsx
> +    setErrorOpen(false);
corrected

2024-02-22 09:20 UTC, deremenko commented on src/components/Page/Main/index.jsx
> +    setNewReception({
corrected

2024-02-22 09:24 UTC, deremenko commented on src/components/Page/Main/index.jsx
> +  const setReception = () => {
maybe corrected

2024-02-22 09:26 UTC, deremenko commented on src/components/Page/Main/index.jsx
> +      <CustomButton
corrected

2024-02-22 09:28 UTC, deremenko commented on src/components/Page/Main/index.jsx
> +        <Reception
corrected

2024-02-22 09:28 UTC, deremenko commented on src/components/Reception/styles.js
> +  }
corrected

2024-02-22 09:29 UTC, deremenko commented on src/components/UI/CustomButton/index.jsx
> +    <StyledButton type={type} onClick={actionButton} className={className}>
corrected

2024-02-22 09:30 UTC, deremenko commented on src/components/UI/CustomButton/index.jsx
> +  className }) => {
corrected

2024-02-22 09:31 UTC, deremenko commented on src/services/user.js
> +  const response = await httpClient.get(`${API_URL}/reception/`);
corrected

2024-02-22 09:36 UTC, deremenko commented on src/services/user.js
> +export const sendReception = async (reception) => {
corrected

2024-02-22 09:36 UTC, deremenko commented on src/services/user.js
> +  const response = await httpClient.post(`${API_URL}/reception/`, reception);
corrected

2024-02-22 09:38 UTC, deremenko commented on src/store/action-creators/user.js
> +    console.log(reception);
corrected

2024-02-22 09:53 UTC, deremenko commented on src/components/Page/Main/index.jsx
> +    setNewReception((prevReception) => ({
corrected

2024-02-22 10:21 UTC, deremenko commented on src/components/Page/Main/index.jsx
> +      patient: newReception.name.value.trim(),
corrected

2024-02-22 10:44 UTC, deremenko commented on src/components/Page/Main/index.jsx
> +        className="big-size-button "
maybe corrected

2024-02-22 10:52 UTC, deremenko commented on src/components/Page/Main/index.jsx
> +          className="resectionInput"
maybe corrected

2024-02-22 11:17 UTC, deremenko commented on src/components/Reception/index.jsx
> +          <StyledTitleText className="name-field">Имя</StyledTitleText>
corrected

2024-02-22 11:17 UTC, deremenko commented on src/components/ReceptionForm/index.jsx
> +      {children}
corrected

2024-02-22 11:54 UTC, deremenko commented on src/http/index.js
> +  return config;
maybe corrected

2024-02-22 12:17 UTC, deremenko commented on src/services/user.js
> +export const requestReceptions = async () => {
corrected

2024-02-22 12:27 UTC, deremenko commented on src/store/action-creators/user.js
> +const createReception = (reception) => async (dispatch) => {
corrected

2024-02-22 12:27 UTC, deremenko commented on src/store/actions/user.js
> +export const getReceptionsError = (error) => ({
corrected

2024-02-22 12:27 UTC, deremenko commented on src/store/reducers/user-reducer.js
> +    case GET_RECEPTIONS_SUCCESS:
corrected

2024-02-22 15:11 UTC, baklanovairina requested changes

2024-02-22 15:11 UTC, baklanovairina commented on src/components/Page/Authorization/index.jsx
> +    navigate("/main");
ну а хок тогда для чего?

2024-02-22 15:11 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +  const tableHeaderOptions = [
в константы это выноси

2024-02-22 15:11 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +    {value: 'Имя', className: '_name'},
эм.. во первых странно в константе писать класс, во вторых у тебя что каждая колонка имеет разный стиль? Что тоже очень странно
В компоненте хэдера таблицы расписывай классы, а не уж точно не в константе

2024-02-22 15:11 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +  const receptions = useSelector((state) => state.reception.receptions);
делай деструктуризацию и за раз все доставай, а не дважды вызывай useSelector

2024-02-22 15:11 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +    submitReception({
ну причем тут submit? это функция на создание приема, так и назови ее createReception

2024-02-22 15:11 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +      complaint: newReception.complaint.value,
а здесь трим?

2024-02-22 15:11 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +          className="_big-size"
та что с неймингом?? Что  за нижнее подчеркивание?

2024-02-22 15:11 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +          className="_horizontal-margin"
и здесь тоже? Везде исправь нейминг классов

2024-02-22 15:11 UTC, baklanovairina commented on src/components/Page/Main/styles.js
> +  grid-area: actions;
и где здесь классы, которые ты использовал в компоненте? Или они все общие и часто повторяются?

2024-02-22 15:11 UTC, baklanovairina commented on src/components/PrivateRoute/index.jsx
> +
здесь должен быть навигейт твой, а не в других компонентах

2024-02-22 15:11 UTC, baklanovairina commented on src/components/Reception/index.jsx
> +<tr key={reception._id}>
табы слетели

зачем здесь key получаешь? Его достаточно просто передавать при мапе

2024-02-22 15:11 UTC, baklanovairina commented on src/components/Reception/index.jsx
> +      className="_icon"
кошмар какой то с неймингом
открывай прошлые проекты и вспоминай

2024-02-22 15:11 UTC, baklanovairina commented on src/components/ReceptionForm/index.jsx
> +      {children}
вообще все убрал отсюда зачем то? Я сказала наоборот добавить сюда поля, а ты все вынеси 
и в чем смысл этого компонента теперь?

2024-02-22 15:11 UTC, baklanovairina commented on src/components/Receptions/index.jsx
> +            <StyledTitleText key={generateUniqueId()} className={option.className}>{option.value}</StyledTitleText>
здесь незачем генерировать ключи уникальные, используй index мапа

2024-02-22 15:11 UTC, baklanovairina commented on src/components/Receptions/index.jsx
> +          <Reception reception = {reception} />
где блин key?
и зачем пробелы в пропсах?

2024-02-22 15:11 UTC, baklanovairina commented on src/components/Receptions/styles.js
> +  &._name {
опачки, откуда вдруг, в компоненте в этом они не используются

2024-02-22 15:11 UTC, baklanovairina commented on src/components/UI/CustomButton/styles.js
> +  &._big-size {
читай выше

2024-02-22 15:11 UTC, baklanovairina commented on src/hook/useActions.js
> +import reception from "../store/action-creators/reception";
чтобы вот так не делать сразу все action-creators импортируй в отдельном файле index.js который будет в папке action-creators

```
import * as UserActionCreators from './user';
// аналогично импортируются остальные ActionCreators

export default {
  ...UserActionCreators,
  // аналогично экспортируются остальные ActionCreators
}
```

а здесь уже будет
```
import AllActionCreators from '../store/action-creators';

const useActions = () => {
  const dispatch = useDispatch();

  return bindActionCreators(AllActionCreators, dispatch);
};
```

2024-02-22 15:11 UTC, baklanovairina commented on src/http/index.js
> +    if (error.response && error.response.status === 401) {
посмотри в том видео, что я кидала, реализацию интерцептора

2024-02-22 15:11 UTC, baklanovairina commented on src/services/user.js
> +  const response = await api.пуе(`${API_URL}/user/refresh`);
пуе??

2024-02-22 15:11 UTC, baklanovairina commented on src/store/action-creators/reception.js
> +const submitReception = (reception) => async (dispatch) => {
про нейминг выше писала

2024-02-23 14:25 UTC, deremenko commented on src/components/Page/Main/index.jsx
> +  const receptions = useSelector((state) => state.reception.receptions);
corrected

2024-02-23 14:29 UTC, deremenko commented on src/components/Page/Main/index.jsx
> +    submitReception({
corrected

2024-02-23 17:08 UTC, deremenko commented on src/components/Page/Authorization/index.jsx
> +    navigate("/main");
maybe corrected

2024-02-23 17:12 UTC, deremenko commented on src/components/Page/Main/index.jsx
> +  const tableHeaderOptions = [
corrected

2024-02-23 17:31 UTC, deremenko commented on src/components/PrivateRoute/index.jsx
> +
corrected

2024-02-23 17:36 UTC, deremenko commented on src/components/Page/Main/index.jsx
> +      complaint: newReception.complaint.value,
corrected

2024-02-23 17:40 UTC, deremenko commented on src/components/Page/Main/styles.js
> +  grid-area: actions;
В какой то момент времени он использовался, но после стал рудиментом и я забыл его удалить...

2024-02-23 17:50 UTC, deremenko commented on src/components/Reception/index.jsx
> +<tr key={reception._id}>
corrected

2024-02-23 17:51 UTC, deremenko commented on src/store/action-creators/reception.js
> +const submitReception = (reception) => async (dispatch) => {
corrected

2024-02-23 18:25 UTC, deremenko commented on src/services/user.js
> +  const response = await api.пуе(`${API_URL}/user/refresh`);
Прошу вас забыть об этом... corrected

2024-02-23 20:07 UTC, deremenko commented on src/components/Receptions/index.jsx
> +            <StyledTitleText key={generateUniqueId()} className={option.className}>{option.value}</StyledTitleText>
corrected

2024-02-24 08:44 UTC, deremenko commented on src/components/Receptions/index.jsx
> +          <Reception reception = {reception} />
corrected

2024-02-24 08:45 UTC, deremenko commented on src/components/Receptions/styles.js
> +  &._name {
corrected

2024-02-24 09:04 UTC, deremenko commented on src/components/Page/Main/index.jsx
> +    {value: 'Имя', className: '_name'},
corrected

2024-02-24 09:41 UTC, deremenko commented on src/components/Reception/index.jsx
> +      className="_icon"
corrected

2024-02-24 09:41 UTC, deremenko commented on src/components/UI/CustomButton/styles.js
> +  &._big-size {
maybe corrected

2024-02-24 10:12 UTC, deremenko commented on src/hook/useActions.js
> +import reception from "../store/action-creators/reception";
corrected

2024-02-24 10:30 UTC, deremenko commented on src/http/index.js
> +    if (error.response && error.response.status === 401) {
maybe corrected

2024-02-27 10:28 UTC, merged