feat: add dialog-action, modal and edit-reception-form
deremenko/hospital-project-frontend--redux-react-styled-component- pull request #6
Opened 2024-02-27 11:37 UTC by deremenko

edit reception function

2024-02-27 13:24 UTC, baklanovairina requested changes

2024-02-27 13:24 UTC, baklanovairina commented on src/components/ActionDialog/index.jsx
> +const ActionDialog = ({
это ModalWindow

2024-02-27 13:24 UTC, baklanovairina commented on src/components/ActionDialog/index.jsx
> +          className="action-dialog-button"
ну и как поправишь нейминг компонента не забудь и стили после этого тоже изменить

2024-02-27 13:24 UTC, baklanovairina commented on src/components/EditReceptionForm/index.jsx
> +    <StyledForm>
а где компонент модального окна?? Который типа обертки с кнопками?? Ты же в него должен оборачивать окно редактировани
а так у тебя не окно редактирования, а просто какая то часть, а смысл в ней???

2024-02-27 13:24 UTC, baklanovairina commented on src/components/EditReceptionForm/index.jsx
> +        />
табы

2024-02-27 13:24 UTC, baklanovairina commented on src/components/Modal/index.jsx
> +  const body = document.body;
не надо так делать
каждый раз при монтировании будет создаваться эа переменная, а зачем? Место занимать?

2024-02-27 13:24 UTC, baklanovairina commented on src/components/Modal/index.jsx
> +const Modal = ({ children }) => {
Portal не Modal

2024-02-27 13:24 UTC, baklanovairina commented on src/components/Modal/index.jsx
> +import React, { useEffect } from 'react';
зачем?

2024-02-27 13:24 UTC, baklanovairina commented on src/components/Modal/index.jsx
> +      <StyledModalContent>
а зачем тебе 2 блока div?? Как будто 1 точно лишни, нет в нем никакого смысла

2024-02-27 13:24 UTC, baklanovairina commented on src/components/Modal/index.jsx
> +    body
сразу напиши document.body

2024-02-27 13:24 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +import ActionDialog from "../../ActionDialog"
а не много ли?? Ты сюда должен только компонент редактирования импортнуть, который у тебя уже должен быть собрать, а не собирать его на главной странице

2024-02-27 13:24 UTC, baklanovairina commented on src/helpers/updateObjectArray.js
> +const updateObjectArray = (
нет, это вообще не хэлперс, это часть логики редактирования, причем не верная
зачем ты используешь тут map? Тебе изменить нужно всего 1 значение, а map будет проходить весь массив до конца

2024-02-27 13:24 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +  const { loadUserReceptions, createReception, logout, changeReception }  = useActions();
где change, где update, не понятно, одна логика или 2? Используй только 1 слово везде, не путай людей

2024-02-27 13:24 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +  const handleUpdateInputChange = (newValue, key) => {
тут уже глагол Change есть зачем еще и Update? Что вообще по сути синоним

2024-02-27 13:24 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +    editWindow: false,
и в чем прикол 2х булево??
одного великолепно хватает 
и нейминг булевых стейтов начинается с is
например isOpenEditModal
и да, у тебя будет 2 стейта - 1 для открытия редактирования, другой для удаления

2024-02-27 13:24 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +    name: {value: '', error: '' },
пробел переде value поставь

2024-02-27 13:24 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +      name: {value: originalReception.patient, error: '' },
тоже пробел перед value

2024-02-27 13:24 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +      ...modalsShow,
а смысл? У тебя там всего 2 свойства, которые ты и перезаписал

2024-02-27 13:24 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +  const [idTargetReception, setIdTargetReception] = useState('');
idUpdatedReception
и будет null, а не пустая строка

2024-02-27 13:24 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +      updatedReceptions,
а зачем ты на бэк оправляешь обновленный массив?? 
ты же там его даже не используешь

2024-02-27 13:24 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +      modal: false,
было 2 непонятных и как будто одинаковых свойства, теперь их 3
потому будет 4?

2024-02-27 13:24 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +      name: {value: '', error: '' },
снова пробел

2024-02-27 13:24 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +      {modalsShow.modal &&
выше писала, отдельные стейты будут и не собираем здесь никакие компоненты кроме главной страницы

2024-02-27 13:24 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +          {modalsShow.editWindow &&
ааа, так вот для чего второе свойство
ну это бред, одного достаточно или у тебя может быть это modalsShow.modal тру, а это вдруг modalsShow.editWindow фолс и будет отображено пустое окно?

2024-02-27 13:24 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +              <EditReceptionForm
и спуская модалки в конец страницы лучше

2024-02-27 13:24 UTC, baklanovairina commented on src/services/reception.js
> +export const editReceptionAPI = async (reception, id) => {
без API
это излишне так писать

2024-02-27 13:24 UTC, baklanovairina commented on src/store/action-creators/reception.js
> +  editReceptionAPI
везде эти апи убирай

2024-02-27 13:24 UTC, baklanovairina commented on src/store/action-creators/reception.js
> +    dispatch(editReceptionSuccess(updateReceptions));
к update и change добавился новый синоним чтобы вконец запутать - edit
Используй только 1 из этих слов

2024-02-27 13:24 UTC, baklanovairina commented on src/store/reducers/reception-reducer.js
> +        receptions: action.payload,
ну тебе же не массив новый возвращается, а 1 новый ресепшен, 
ты не можешь отсюда выносить изменения, иначе увеличивается зависимость 
вот там где ты сделал функцию хэлперс с мап, вот она должна быть здесь и ты уже в компонент возвращаешь обновленный массив
а не обновляешь его где то за пределами редьюсера

2024-02-27 14:19 UTC, deremenko commented on src/components/ActionDialog/index.jsx
> +const ActionDialog = ({
corrected

2024-02-27 14:27 UTC, deremenko commented on src/components/ActionDialog/index.jsx
> +          className="action-dialog-button"
corrected

2024-02-27 14:27 UTC, deremenko commented on src/components/EditReceptionForm/index.jsx
> +    <StyledForm>
corrected

2024-02-27 14:28 UTC, deremenko commented on src/components/EditReceptionForm/index.jsx
> +        />
corrected

2024-02-27 14:28 UTC, deremenko commented on src/components/Modal/index.jsx
> +  const body = document.body;
corrected

2024-02-27 14:28 UTC, deremenko commented on src/components/Modal/index.jsx
> +const Modal = ({ children }) => {
corrected

2024-02-27 14:28 UTC, deremenko commented on src/components/Modal/index.jsx
> +import React, { useEffect } from 'react';
corrected

2024-02-27 14:28 UTC, deremenko commented on src/components/Modal/index.jsx
> +      <StyledModalContent>
corrected

2024-02-27 14:28 UTC, deremenko commented on src/components/Modal/index.jsx
> +    body
corrected

2024-02-27 14:28 UTC, deremenko commented on src/components/Page/Main/index.jsx
> +import ActionDialog from "../../ActionDialog"
corrected

2024-02-27 14:30 UTC, deremenko commented on src/components/Page/Main/index.jsx
> +    editWindow: false,
corrected

2024-02-27 14:32 UTC, deremenko commented on src/components/Page/Main/index.jsx
> +      ...modalsShow,
corrected

2024-02-27 14:32 UTC, deremenko commented on src/components/Page/Main/index.jsx
> +  const [idTargetReception, setIdTargetReception] = useState('');
corrected

2024-02-27 14:36 UTC, deremenko commented on src/components/Page/Main/index.jsx
> +      modal: false,
corrected

2024-02-27 14:50 UTC, deremenko commented on src/components/Page/Main/index.jsx
> +    name: {value: '', error: '' },
corrected

2024-02-27 14:50 UTC, deremenko commented on src/components/Page/Main/index.jsx
> +      name: {value: originalReception.patient, error: '' },
corrected

2024-02-27 14:50 UTC, deremenko commented on src/components/Page/Main/index.jsx
> +      updatedReceptions,
corrected

2024-02-27 14:50 UTC, deremenko commented on src/components/Page/Main/index.jsx
> +      name: {value: '', error: '' },
corrected

2024-02-27 14:50 UTC, deremenko commented on src/components/Page/Main/index.jsx
> +      {modalsShow.modal &&
corrected

2024-02-27 14:52 UTC, deremenko commented on src/components/Page/Main/index.jsx
> +          {modalsShow.editWindow &&
Вот --это бред-- даже как то обидно было, сказали бы просто избыточно 
corrected

2024-02-27 14:52 UTC, deremenko commented on src/components/Page/Main/index.jsx
> +              <EditReceptionForm
corrected

2024-02-27 14:54 UTC, deremenko commented on src/store/reducers/reception-reducer.js
> +        receptions: action.payload,
corrected

2024-02-28 08:13 UTC, baklanovairina requested changes

2024-02-28 08:13 UTC, baklanovairina commented on src/components/EditReceptionModal/index.jsx
> +    <Portal>
зачем он здесь? 
оберни в него сразу ModalWindow, чтобы постоянно не вызывать его лишний раз
ModalWindow всегда будет в Portal
а здесь уже просто ModalWindow вызовешь только

2024-02-28 08:13 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +  const [idTargetReception, setIdTargetReception] = useState(null);
я просила ранее поправить здесь нейминг на idUpdatedReception

2024-02-28 08:13 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +  const [isOpenEditModa, setIsOpenEditModa] = useState(false);
Moda?? что за мода?

2024-02-28 08:13 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +      name: {value: originalReception.patient, error: '' },
точно corrected?

2024-02-28 08:13 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +      doctor: { value: '', error: ''  },
и зачем после error: '' два пробела ставить? Одного думаешь мало?

2024-02-28 08:20 UTC, deremenko commented on src/components/Page/Main/index.jsx
> +  const [isOpenEditModa, setIsOpenEditModa] = useState(false);
corrected

2024-02-28 08:21 UTC, deremenko commented on src/components/Page/Main/index.jsx
> +  const [idTargetReception, setIdTargetReception] = useState(null);
corrected

2024-02-28 08:21 UTC, deremenko commented on src/components/EditReceptionModal/index.jsx
> +    <Portal>
corrected

2024-02-28 08:23 UTC, deremenko commented on src/components/Page/Main/index.jsx
> +  const [isOpenEditModa, setIsOpenEditModa] = useState(false);
corrected

2024-02-28 08:23 UTC, deremenko commented on src/components/Page/Main/index.jsx
> +      doctor: { value: '', error: ''  },
corrected

2024-02-28 09:56 UTC, merged