feat: add sort for column
deremenko/hospital-project-frontend--redux-react-styled-component- pull request #8
Opened 2024-02-28 13:41 UTC by deremenko

sort logic and component

2024-02-28 15:14 UTC, baklanovairina requested changes

2024-02-28 15:14 UTC, baklanovairina commented on src/components/ColumnSortingInterface/index.jsx
> +const ColumnSortingInterface = ({
какое страшное название, причем тут колонки? Зачем указывать, что это интерфейс? А то прям не понятно?

Это просто форма сортировки

2024-02-28 15:14 UTC, baklanovairina commented on src/components/ColumnSortingInterface/index.jsx
> +        actionSelector={setSortColumnName}
опачки, а чего это мы состояние изменяем в других компонентах? 
Это база - мы уже говорили, что пропсы не изменяемые и стейты значит не могут изменяться в других компонентах, а только там где созданы

2024-02-28 15:14 UTC, baklanovairina commented on src/components/ColumnSortingInterface/index.jsx
> +      <span>Сортироват по:</span>
СортироватЬ

2024-02-28 15:14 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +  const [sortColumnName, setSortColumnName] = useState('None');
давай без None, так никто не пишет на сайтах, просто пустое
и это не Column

2024-02-28 15:14 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +  const [sortDirection, setSortDirection] = useState('По возрастанию');
1 стейт вместо двух, так как это форма сортировки, поля работают вместе и по сути зависимы друг от друга

2024-02-28 15:14 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +      sortedReceptions.sort((a, b) => {
функцию сортировки массива вообще выноси в хэлперс, она должна подходить для всего

2024-02-28 15:14 UTC, baklanovairina commented on src/components/ColumnSortingInterface/index.jsx
> +        <CustomSelector
а что у тебя кастомный селектор не предусматривает label? 
Добавь значит
и сразу фрагмент исчезнет

2024-02-28 15:14 UTC, baklanovairina commented on src/components/ColumnSortingInterface/index.jsx
> +        <CustomSelector
Направление  и Сортироват по:
это label, а не span

2024-02-28 15:14 UTC, baklanovairina commented on src/components/Page/Main/index.jsx
> +    return sortedReceptions
я что-то не нашла, где ты обновляешь состояния всех респешенов, после сортировки? 
и тебе также нужен бэкап стейт для чтобы сохранять первоначальный массива приемов и если сбросить сортировку, он должен вернуться к нему

2024-02-29 07:53 UTC, deremenko commented on src/components/ColumnSortingInterface/index.jsx
> +const ColumnSortingInterface = ({
corrected

2024-02-29 08:11 UTC, deremenko commented on src/components/ColumnSortingInterface/index.jsx
> +      <span>Сортироват по:</span>
corrected

2024-02-29 08:48 UTC, deremenko commented on src/components/Page/Main/index.jsx
> +  const [sortDirection, setSortDirection] = useState('По возрастанию');
corrected

2024-02-29 08:48 UTC, deremenko commented on src/components/Page/Main/index.jsx
> +      sortedReceptions.sort((a, b) => {
corrected

2024-02-29 08:48 UTC, deremenko commented on src/components/ColumnSortingInterface/index.jsx
> +        <CustomSelector
corrected

2024-02-29 09:02 UTC, deremenko commented on src/components/ColumnSortingInterface/index.jsx
> +        actionSelector={setSortColumnName}
corrected

2024-02-29 09:04 UTC, deremenko commented on src/components/Page/Main/index.jsx
> +  const [sortColumnName, setSortColumnName] = useState('None');
corrected

2024-02-29 09:15 UTC, deremenko commented on src/components/Page/Main/index.jsx
> +    return sortedReceptions
corrected

2024-02-29 13:05 UTC, merged